export type PublishedDepthSide = "offense" | "defense" | "specialists";

export type PublishedDepthEntry = {
  side: PublishedDepthSide;
  role: string;
  position: string;
  depth: number;
  player: string;
  jersey: number | null;
};

export type PublishedDepthChart = {
  season: number;
  team: string;
  label: string;
  publishedAt: string;
  sourceUrl: string;
  sourceKind:
    | "official_game_notes"
    | "official_media_guide"
    | "official_gamebook"
    | "conference_game_notes"
    | "licensed_provider"
    | "observed_starters";
  entries: PublishedDepthEntry[];
};

const entry = (
  side: PublishedDepthSide,
  role: string,
  position: string,
  depth: number,
  player: string,
  jersey: number | null,
): PublishedDepthEntry => ({ side, role, position, depth, player, jersey });

/**
 * Published team depth charts are facts, not model outputs. They are kept as a
 * separate overlay so a sourced role always defeats roster-label inference.
 *
 * This small verified set also acts as an integration fixture for the importer
 * that will accept licensed provider feeds or additional official team notes.
 */
const charts: PublishedDepthChart[] = [
  {
    season: 2015,
    team: "Alabama",
    label: "Alabama football game notes",
    publishedAt: "2015-10-08",
    sourceUrl: "https://rolltide.com/documents/download/2015/10/8/release_20151008aaa.pdf",
    sourceKind: "official_game_notes",
    entries: [
      entry("offense", "LT", "LT", 1, "Cam Robinson", 74),
      entry("offense", "LT", "LT", 2, "Lester Cotton", 66),
      entry("offense", "LG", "LG", 1, "Ross Pierschbacher", 71),
      entry("offense", "LG", "LG", 2, "Dallas Warmack", 59),
      entry("offense", "C", "C", 1, "Ryan Kelly", 70),
      entry("offense", "C", "C", 2, "J.C. Hassenauer", 63),
      entry("offense", "RG", "RG", 1, "Alphonse Taylor", 50),
      entry("offense", "RG", "RG", 2, "Bradley Bozeman", 75),
      entry("offense", "RT", "RT", 1, "Dominick Jackson", 76),
      entry("offense", "RT", "RT", 2, "Brandon Greene", 58),
      entry("offense", "Y", "TE", 1, "Dakota Ball", 94),
      entry("offense", "Y", "TE", 2, "Hale Hentges", 84),
      entry("offense", "H", "TE", 1, "O.J. Howard", 88),
      entry("offense", "H", "TE", 2, "Ty Flournoy-Smith", 83),
      entry("offense", "QB", "QB", 1, "Jake Coker", 14),
      entry("offense", "QB", "QB", 2, "Cooper Bateman", 18),
      entry("offense", "RB", "RB", 1, "Derrick Henry", 2),
      entry("offense", "RB", "RB", 2, "Kenyan Drake", 17),
      entry("offense", "Z", "WR", 1, "ArDarius Stewart", 13),
      entry("offense", "Z", "WR", 2, "Cam Sims", 7),
      entry("offense", "X", "WR", 1, "Calvin Ridley", 3),
      entry("offense", "X", "WR", 2, "Daylon Charlot", 4),
      entry("offense", "SLOT", "WR", 1, "Richard Mullaney", 16),
      entry("offense", "SLOT", "WR", 2, "Chris Black", 1),
      entry("defense", "DE", "DE", 1, "A'Shawn Robinson", 86),
      entry("defense", "DE", "DE", 2, "Jonathan Allen", 93),
      entry("defense", "NT", "NT", 1, "Darren Lake", 95),
      entry("defense", "NT", "NT", 2, "Daron Payne", 94),
      entry("defense", "DT", "DT", 1, "Jarran Reed", 90),
      entry("defense", "DT", "DT", 2, "Dalvin Tomlinson", 54),
      entry("defense", "JACK", "EDGE", 1, "Denzel Devall", 30),
      entry("defense", "JACK", "EDGE", 2, "Ryan Anderson", 22),
      entry("defense", "SAM", "OLB", 1, "Dillon Lee", 25),
      entry("defense", "SAM", "OLB", 2, "Rashaan Evans", 32),
      entry("defense", "MIKE", "MLB", 1, "Reggie Ragland", 19),
      entry("defense", "MIKE", "MLB", 2, "Dillon Lee", 25),
      entry("defense", "WILL", "ILB", 1, "Reuben Foster", 10),
      entry("defense", "WILL", "ILB", 2, "Shaun Dion Hamilton", 20),
      entry("defense", "CB", "CB", 1, "Cyrus Jones", 5),
      entry("defense", "CB", "CB", 2, "Bradley Sylve", 3),
      entry("defense", "CB", "CB", 1, "Marlon Humphrey", 26),
      entry("defense", "CB", "CB", 2, "Tony Brown", 7),
      entry("defense", "SS", "SS", 1, "Eddie Jackson", 4),
      entry("defense", "SS", "SS", 2, "Ronnie Harrison", 15),
      entry("defense", "FS", "FS", 1, "Geno Matias-Smith", 24),
      entry("defense", "FS", "FS", 2, "Laurence Hootie Jones", 6),
      entry("defense", "STAR", "NB", 1, "Minkah Fitzpatrick", 29),
      entry("defense", "STAR", "NB", 2, "Tony Brown", 7),
      entry("specialists", "K", "K", 1, "Adam Griffith", 99),
      entry("specialists", "P", "P", 1, "JK Scott", 15),
      entry("specialists", "LS", "LS", 1, "Cole Mazza", 55),
    ],
  },
  {
    season: 2025,
    team: "Alabama",
    label: "Alabama SEC Championship game notes",
    publishedAt: "2025-12-01",
    sourceUrl: "https://rolltide.com/documents/download/2025/12/1/12.6.25_Georgia.pdf",
    sourceKind: "official_game_notes",
    entries: [
      entry("offense", "LT", "LT", 1, "Kadyn Proctor", 74),
      entry("offense", "LT", "LT", 2, "Jackson Lloyd", 78),
      entry("offense", "LG", "LG", 1, "Kam Dewberry", 71),
      entry("offense", "LG", "LG", 2, "William Sanders", 70),
      entry("offense", "C", "C", 1, "Parker Brailsford", 72),
      entry("offense", "C", "C", 2, "Joseph Ionata", 69),
      entry("offense", "RG", "RG", 1, "Geno VanDeMark", 56),
      entry("offense", "RG", "RG", 2, "Jaeden Roberts", 77),
      entry("offense", "RT", "RT", 1, "Wilkin Formby", 75),
      entry("offense", "RT", "RT", 2, "Michael Carroll", 64),
      entry("offense", "Y", "TE", 1, "Kaleb Edwards", 81),
      entry("offense", "Y", "TE", 2, "Jay Lindsey", 88),
      entry("offense", "H", "TE", 1, "Josh Cuevas", 80),
      entry("offense", "H", "TE", 2, "Marshall Pritchett", 14),
      entry("offense", "QB", "QB", 1, "Ty Simpson", 15),
      entry("offense", "QB", "QB", 2, "Austin Mack", 10),
      entry("offense", "RB", "RB", 1, "Jam Miller", 26),
      entry("offense", "RB", "RB", 2, "Daniel Hill", 4),
      entry("offense", "Z", "WR", 1, "Germie Bernard", 5),
      entry("offense", "Z", "WR", 2, "Rico Scott", 11),
      entry("offense", "X", "WR", 1, "Isaiah Horton", 1),
      entry("offense", "X", "WR", 2, "Derek Meadows", 30),
      entry("offense", "SLOT", "WR", 1, "Ryan Williams", 2),
      entry("offense", "SLOT", "WR", 2, "Lotzeir Brooks", 17),
      entry("defense", "BANDIT", "EDGE", 1, "LT Overton", 22),
      entry("defense", "BANDIT", "EDGE", 2, "Jordan Renaud", 11),
      entry("defense", "NT", "NT", 1, "Tim Keenan III", 96),
      entry("defense", "NT", "NT", 2, "London Simmons", 90),
      entry("defense", "DT", "DT", 1, "James Smith", 23),
      entry("defense", "DT", "DT", 2, "Edric Hill", 94),
      entry("defense", "WOLF", "EDGE", 1, "Yhonzae Pierre", 42),
      entry("defense", "WOLF", "EDGE", 2, "Qua Russaw", 4),
      entry("defense", "STINGER", "ILB", 1, "Deontae Lawson", 0),
      entry("defense", "STINGER", "ILB", 2, "Nikhai Hill-Green", 41),
      entry("defense", "MIKE", "MLB", 1, "Justin Jefferson", 10),
      entry("defense", "MIKE", "MLB", 2, "QB Reese", 36),
      entry("defense", "CB", "CB", 1, "Dijon Lee Jr.", 5),
      entry("defense", "CB", "CB", 2, "Domani Jackson", 1),
      entry("defense", "CB", "CB", 1, "Zabien Brown", 2),
      entry("defense", "CB", "CB", 2, "Cam Calhoun", 9),
      entry("defense", "FS", "FS", 1, "Bray Hubbard", 18),
      entry("defense", "FS", "FS", 2, "Zavier Mincey", 12),
      entry("defense", "SS", "SS", 1, "Keon Sabb", 3),
      entry("defense", "SS", "SS", 2, "Ivan Taylor", 13),
      entry("defense", "HUSKY", "NB", 1, "DaShawn Jones", 7),
      entry("defense", "HUSKY", "NB", 2, "Red Morgan", 16),
      entry("specialists", "K", "K", 1, "Conor Talty", 31),
      entry("specialists", "P", "P", 1, "Blake Doud", 38),
      entry("specialists", "LS", "LS", 1, "David Bird", 45),
    ],
  },
  {
    season: 2014,
    team: "UL Monroe",
    label: "ULM football game notes at Arkansas State",
    publishedAt: "2014-10-04",
    sourceUrl: "https://ulm_ftp.sidearmsports.com/pdf9/2863622.pdf",
    sourceKind: "official_game_notes",
    entries: [
      entry("offense", "QB", "QB", 1, "Pete Thomas", 14),
      entry("offense", "QB", "QB", 2, "Brayle Brown", 12),
      entry("offense", "RB", "RB", 1, "Centarius Donald", 5),
      entry("offense", "RB", "RB", 2, "Tyler Cain", 3),
      entry("offense", "WR", "WR", 1, "Ajalen Holley", 21),
      entry("offense", "WR", "WR", 2, "Tony Cook", 80),
      entry("offense", "WR", "WR", 1, "Rashon Ceaser", 2),
      entry("offense", "WR", "WR", 2, "Shakeem Jefferson", 81),
      entry("offense", "WR", "WR", 1, "Kenzee Jackson", 23),
      entry("offense", "WR", "WR", 2, "Tyrone Carter", 16),
      entry("offense", "TE", "TE", 1, "Alec Osborne", 89),
      entry("offense", "TE", "TE", 2, "Harley Scioneaux", 88),
      entry("offense", "RT", "RT", 1, "Chase Regian", 71),
      entry("offense", "RT", "RT", 2, "Jeremy Burton", 67),
      entry("offense", "RG", "RG", 1, "Ben Risenhoover", 77),
      entry("offense", "RG", "RG", 2, "Jimmy Chung", 55),
      entry("offense", "C", "C", 1, "Colby Mitchell", 68),
      entry("offense", "C", "C", 2, "Trey Martin", 73),
      entry("offense", "LG", "LG", 1, "Demiere Burkett", 75),
      entry("offense", "LG", "LG", 2, "Matt Oubre", 74),
      entry("offense", "LT", "LT", 1, "Joseph Treadwell", 65),
      entry("offense", "LT", "LT", 2, "Frank Sutton Jr.", 70),
      entry("defense", "DE", "DE", 1, "Lorenzo Jackson", 45),
      entry("defense", "DE", "DE", 2, "Jacob Tyson", 51),
      entry("defense", "NT", "NT", 1, "Gerrand Johnson", 76),
      entry("defense", "NT", "NT", 2, "David Elias Jr.", 91),
      entry("defense", "DE", "DE", 1, "Joey Gautney", 99),
      entry("defense", "DE", "DE", 2, "Malcolm Edmond", 98),
      entry("defense", "LB", "LB", 1, "Ray Stovall", 90),
      entry("defense", "LB", "LB", 2, "Tevyn Cagins", 33),
      entry("defense", "LB", "LB", 1, "Hunter Kissinger", 48),
      entry("defense", "LB", "LB", 2, "Braxton Moore", 57),
      entry("defense", "LB", "LB", 1, "Michael Johnson", 34),
      entry("defense", "LB", "LB", 2, "Cody Robinson", 36),
      entry("defense", "CB", "CB", 1, "Rob'Donovan Lewis", 1),
      entry("defense", "CB", "CB", 2, "Junior Williams", 8),
      entry("defense", "S", "S", 1, "Cordero Smith", 10),
      entry("defense", "S", "S", 2, "Tre' Hunter", 4),
      entry("defense", "H", "NB", 1, "Mitch Lane", 7),
      entry("defense", "H", "NB", 2, "Bryce Ray", 43),
      entry("defense", "S", "S", 1, "Justin Backus", 20),
      entry("defense", "S", "S", 2, "Roland Veal", 42),
      entry("defense", "CB", "CB", 1, "Ferrando Joseph", 29),
      entry("defense", "CB", "CB", 2, "Grant Dotsy", 27),
      entry("specialists", "K", "K", 1, "Justin Manton", 17),
      entry("specialists", "K", "K", 2, "Craig Ford", 60),
      entry("specialists", "P", "P", 1, "Justin Manton", 17),
      entry("specialists", "P", "P", 2, "Craig Ford", 60),
      entry("specialists", "LS", "LS", 1, "Todd Phillips", 44),
      entry("specialists", "LS", "LS", 2, "Nick Jones", 87),
      entry("specialists", "SSNAP", "LS", 1, "Ben Risenhoover", 77),
      entry("specialists", "SSNAP", "LS", 2, "Todd Phillips", 44),
      entry("specialists", "H", "QB", 1, "Brayle Brown", 12),
      entry("specialists", "H", "WR", 2, "Ajalen Holley", 21),
      entry("specialists", "KR", "KR", 1, "Tyler Cain", 3),
      entry("specialists", "KR", "KR", 2, "Kenzee Jackson", 23),
      entry("specialists", "PR", "PR", 1, "Rashon Ceaser", 2),
      entry("specialists", "PR", "PR", 2, "Junior Williams", 8),
    ],
  },
  {
    season: 2014,
    team: "Arkansas State",
    label: "Arkansas State football opening-game notes",
    publishedAt: "2014-08-30",
    sourceUrl: "https://arkansasstu_ftp.sidearmsports.com/pdf9/2768961.pdf",
    sourceKind: "official_game_notes",
    entries: [
      entry("offense", "LT", "LT", 1, "Jemar Clark", 79),
      entry("offense", "LT", "LT", 2, "Daniel Keith", 77),
      entry("offense", "LG", "LG", 1, "Devin Mondie", 74),
      entry("offense", "LG", "LG", 2, "Steven Stevens", 71),
      entry("offense", "C", "C", 1, "Tyler Greve", 58),
      entry("offense", "C", "C", 2, "Kyle Harris", 70),
      entry("offense", "C", "C", 2, "Jonathan Hamilton", null),
      entry("offense", "RG", "RG", 1, "Alan Wright", 69),
      entry("offense", "RG", "RG", 2, "Austin Moreton", 76),
      entry("offense", "RT", "RT", 1, "Colton Jackson", 61),
      entry("offense", "RT", "RT", 2, "Brennan Tutor", 72),
      entry("offense", "QB", "QB", 1, "Fredi Knighten", 9),
      entry("offense", "QB", "QB", 2, "Stephen Hogan", 8),
      entry("offense", "RB", "RB", 1, "Michael Gordon", 34),
      entry("offense", "RB", "RB", 2, "Johnston White", 30),
      entry("offense", "A", "RB", 1, "J.D. McKissic", 23),
      entry("offense", "A", "RB", 2, "Brandon Cox", 20),
      entry("offense", "Y", "TE", 1, "Darion Griswold", 19),
      entry("offense", "Y", "TE", 2, "Warren Leapheart", 82),
      entry("offense", "H", "TE", 1, "Kenneth Rains", 87),
      entry("offense", "H", "TE", 2, "Jerry Moorehead", 86),
      entry("offense", "WR", "WR", 1, "Dijon Paschal", 84),
      entry("offense", "WR", "WR", 2, "Booker Mayes", 18),
      entry("offense", "WR", "WR", 1, "Tres Houston", 15),
      entry("offense", "WR", "WR", 2, "Carl Lee Jr.", 81),
      entry("defense", "DE", "DE", 1, "Ja'Von Rolland-Jones", 37),
      entry("defense", "DE", "DE", 2, "Jonah Hill", 88),
      entry("defense", "NT", "NT", 1, "Darrius Rosser", 92),
      entry("defense", "NT", "NT", 2, "Clifford Thomas", 98),
      entry("defense", "DT", "DT", 1, "Dexter Blackmon", 77),
      entry("defense", "DT", "DT", 2, "E.J. Sutton", 96),
      entry("defense", "BANDIT", "EDGE", 1, "Chris Stone", 42),
      entry("defense", "BANDIT", "EDGE", 2, "Chris Odom", 93),
      entry("defense", "BANDIT", "EDGE", 3, "Jabari Mathieu", 99),
      entry("defense", "WILL", "ILB", 1, "Xavier Woodson", 55),
      entry("defense", "WILL", "ILB", 2, "Khari Lain", 9),
      entry("defense", "MIKE", "MLB", 1, "Qushaun Lee", 48),
      entry("defense", "MIKE", "MLB", 2, "Austin Copeland", 50),
      entry("defense", "NB", "NB", 1, "Charleston Girley", 8),
      entry("defense", "NB", "NB", 2, "Frankie Jackson", 6),
      entry("defense", "CB", "CB", 1, "Artez Brown", 10),
      entry("defense", "CB", "CB", 2, "Blaise Taylor", 1),
      entry("defense", "CB", "CB", 3, "Jamaris Hart", 17),
      entry("defense", "SS", "SS", 1, "Chris Humes", 29),
      entry("defense", "SS", "SS", 2, "Money Hunter", 27),
      entry("defense", "FS", "FS", 1, "Sterling Young", 11),
      entry("defense", "FS", "FS", 2, "Sterling Wright", 4),
      entry("defense", "CB", "CB", 1, "Andrew Tryon", 21),
      entry("defense", "CB", "CB", 2, "Rocky Hayes", 3),
      entry("specialists", "K", "K", 1, "Luke Ferguson", 15),
      entry("specialists", "K", "K", 2, "Dallas Kepler", 36),
      entry("specialists", "P", "P", 1, "Luke Ferguson", 15),
      entry("specialists", "P", "P", 1, "Stephen Hogan", 8),
      entry("specialists", "KR", "KR", 1, "J.D. McKissic", 23),
      entry("specialists", "KR", "KR", 2, "Brandon Cox", 20),
      entry("specialists", "KR", "KR", 3, "Blaise Taylor", 1),
      entry("specialists", "PR", "PR", 1, "J.D. McKissic", 23),
      entry("specialists", "PR", "PR", 2, "Blaise Taylor", 1),
      entry("specialists", "LS", "LS", 1, "Ryan Eustace", 45),
      entry("specialists", "LS", "LS", 2, "Bryan Scanlan", 47),
      entry("specialists", "H", "QB", 1, "Stephen Hogan", 8),
    ],
  },
  {
    season: 2015,
    team: "Michigan",
    label: "Michigan football game notes at Maryland",
    publishedAt: "2015-10-03",
    sourceUrl: "https://maryland_ftp.sidearmsports.com/custompages/pdf/football/Mich_GameNotes.pdf",
    sourceKind: "official_game_notes",
    entries: [
      entry("offense", "WR", "WR", 1, "Amara Darboh", 82),
      entry("offense", "WR", "WR", 2, "Maurice Ways", 85),
      entry("offense", "WR", "WR", 3, "Drake Harris", 14),
      entry("offense", "LT", "LT", 1, "Mason Cole", 52),
      entry("offense", "LT", "LT", 2, "Grant Newsome", 77),
      entry("offense", "LG", "LG", 1, "Ben Braden", 71),
      entry("offense", "LG", "LG", 2, "David Dawson", 55),
      entry("offense", "C", "C", 1, "Graham Glasgow", 61),
      entry("offense", "C", "C", 2, "Patrick Kugler", 57),
      entry("offense", "C", "C", 3, "Ben Pliska", 63),
      entry("offense", "RG", "RG", 1, "Kyle Kalis", 67),
      entry("offense", "RG", "RG", 2, "Juwan Bushell-Beatty", 76),
      entry("offense", "RT", "RT", 1, "Erik Magnuson", 78),
      entry("offense", "RT", "RT", 2, "Blake Bars", 62),
      entry("offense", "TE", "TE", 1, "Jake Butt", 88),
      entry("offense", "TE", "TE", 2, "Ian Bunting", 89),
      entry("offense", "TE", "TE", 2, "A.J. Williams", 84),
      entry("offense", "TE", "TE", 2, "Khalid Hill", 80),
      entry("offense", "TE", "TE", 3, "Michael Jocz", 81),
      entry("offense", "TE", "TE", 3, "Chase Winovich", 44),
      entry("offense", "WR", "WR", 1, "Jehu Chesson", 86),
      entry("offense", "WR", "WR", 2, "Freddy Canteen", 17),
      entry("offense", "WR", "WR", 3, "Grant Perry", 9),
      entry("offense", "QB", "QB", 1, "Jake Rudock", 15),
      entry("offense", "QB", "QB", 2, "Shane Morris", 7),
      entry("offense", "QB", "QB", 3, "Wilton Speight", 3),
      entry("offense", "FB", "FB", 1, "Joe Kerridge", 36),
      entry("offense", "FB", "FB", 2, "Henry Poggi", 19),
      entry("offense", "FB", "FB", 3, "Sione Houma", 39),
      entry("offense", "RB", "RB", 1, "De'Veon Smith", 4),
      entry("offense", "RB", "RB", 2, "Ty Isaac", 32),
      entry("offense", "RB", "RB", 2, "Derrick Green", 27),
      entry("offense", "RB", "RB", 2, "Drake Johnson", 20),
      entry("offense", "RB", "RB", 3, "Ross Taylor-Douglas", 29),
      entry("offense", "RB", "RB", 3, "Karan Higdon", 22),
      entry("defense", "DE", "DE", 1, "Willie Henry", 69),
      entry("defense", "DE", "DE", 2, "Taco Charlton", 33),
      entry("defense", "NT", "NT", 1, "Ryan Glasgow", 96),
      entry("defense", "NT", "NT", 2, "Maurice Hurst", 73),
      entry("defense", "DT", "DT", 1, "Chris Wormley", 43),
      entry("defense", "DT", "DT", 1, "Matt Godin", 99),
      entry("defense", "BUCK", "EDGE", 1, "Mario Ojemudia", 53),
      entry("defense", "BUCK", "EDGE", 2, "Royce Jenkins-Stone", 52),
      entry("defense", "BUCK", "EDGE", 3, "Lawrence Marshall", 93),
      entry("defense", "ILB", "ILB", 1, "Desmond Morgan", 3),
      entry("defense", "ILB", "ILB", 2, "Ben Gedeon", 42),
      entry("defense", "ILB", "ILB", 3, "Mike McCray", 9),
      entry("defense", "ILB", "ILB", 1, "Joe Bolden", 35),
      entry("defense", "ILB", "ILB", 2, "James Ross", 15),
      entry("defense", "OLB", "OLB", 1, "James Ross", 15),
      entry("defense", "OLB", "OLB", 2, "Allen Gant", 14),
      entry("defense", "CB", "CB", 1, "Jourdan Lewis", 26),
      entry("defense", "CB", "CB", 2, "Jeremy Clark", 34),
      entry("defense", "FS", "FS", 1, "Jarrod Wilson", 22),
      entry("defense", "FS", "FS", 2, "Delano Hill", 44),
      entry("defense", "SS", "SS", 1, "Jabrill Peppers", 5),
      entry("defense", "SS", "SS", 2, "Dymonte Thomas", 25),
      entry("defense", "SS", "SS", 3, "Wayne Lyons", 24),
      entry("defense", "CB", "CB", 1, "Channing Stribling", 8),
      entry("defense", "CB", "CB", 2, "Brandon Watson", 28),
      entry("specialists", "K", "K", 1, "Kenny Allen", 91),
      entry("specialists", "K", "K", 2, "Kyle Seychel", 3),
      entry("specialists", "P", "P", 1, "Blake O'Neill", 12),
      entry("specialists", "P", "P", 1, "Kenny Allen", 91),
      entry("specialists", "LS", "LS", 1, "Scott Sypniewski", 31),
      entry("specialists", "LS", "LS", 2, "Andrew Robinson", 50),
      entry("specialists", "H", "P", 1, "Blake O'Neill", 12),
      entry("specialists", "H", "QB", 2, "Jake Rudock", 15),
      entry("specialists", "KO", "K", 1, "Kenny Allen", 91),
      entry("specialists", "KO", "K", 2, "Kyle Seychel", 31),
      entry("specialists", "KR", "KR", 1, "Jabrill Peppers", 5),
      entry("specialists", "KR", "KR", 2, "Jourdan Lewis", 26),
      entry("specialists", "KR", "KR", 3, "Dymonte Thomas", 25),
      entry("specialists", "PR", "PR", 1, "Jabrill Peppers", 5),
      entry("specialists", "PR", "PR", 2, "Jourdan Lewis", 26),
      entry("specialists", "PR", "PR", 3, "Jehu Chesson", 86),
    ],
  },
];

const key = (season: number, team: string) =>
  `${season}:${team.toLowerCase().replace(/[^a-z0-9]/g, "")}`;

const chartByTeamSeason = new Map(charts.map((chart) => [key(chart.season, chart.team), chart]));

export function getPublishedDepthChart(season: number, team: string) {
  return chartByTeamSeason.get(key(season, team)) ?? null;
}

export function listPublishedDepthCharts() {
  return charts.map((chart) => ({
    ...chart,
    entries: chart.entries.map((depthEntry) => ({ ...depthEntry })),
  }));
}
